; ─── Shared base (tidak di-build langsung) ───────────────────────
[common]
platform       = espressif32
board          = esp32dev
framework      = arduino
monitor_speed  = 115200
lib_ldf_mode   = deep+
lib_extra_dirs = lib
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    knolleary/PubSubClient @ ^2.8

; ─── Production (default) ────────────────────────────────────────
[env:release]
extends     = common
build_flags = -D DEBUG_MODE=0

; ─── Development ─────────────────────────────────────────────────
[env:debug]
extends     = common
build_flags = -D DEBUG_MODE=1

; ─── Test ────────────────────────────────────────────────────────
[env:test]
extends        = common
test_framework = unity
test_filter    = test_*